/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SeoTaskService } from "../seoTask.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SeoTaskCreateInput } from "./SeoTaskCreateInput";
import { SeoTask } from "./SeoTask";
import { SeoTaskFindManyArgs } from "./SeoTaskFindManyArgs";
import { SeoTaskWhereUniqueInput } from "./SeoTaskWhereUniqueInput";
import { SeoTaskUpdateInput } from "./SeoTaskUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SeoTaskControllerBase {
  constructor(
    protected readonly service: SeoTaskService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SeoTask })
  @nestAccessControl.UseRoles({
    resource: "SeoTask",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSeoTask(
    @common.Body() data: SeoTaskCreateInput
  ): Promise<SeoTask> {
    return await this.service.createSeoTask({
      data: data,
      select: {
        country: true,
        createdAt: true,
        id: true,
        keyword: true,
        language: true,
        location: true,
        results: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SeoTask] })
  @ApiNestedQuery(SeoTaskFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SeoTask",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async seoTasks(@common.Req() request: Request): Promise<SeoTask[]> {
    const args = plainToClass(SeoTaskFindManyArgs, request.query);
    return this.service.seoTasks({
      ...args,
      select: {
        country: true,
        createdAt: true,
        id: true,
        keyword: true,
        language: true,
        location: true,
        results: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SeoTask })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SeoTask",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async seoTask(
    @common.Param() params: SeoTaskWhereUniqueInput
  ): Promise<SeoTask | null> {
    const result = await this.service.seoTask({
      where: params,
      select: {
        country: true,
        createdAt: true,
        id: true,
        keyword: true,
        language: true,
        location: true,
        results: true,
        updatedAt: true,
        url: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SeoTask })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SeoTask",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSeoTask(
    @common.Param() params: SeoTaskWhereUniqueInput,
    @common.Body() data: SeoTaskUpdateInput
  ): Promise<SeoTask | null> {
    try {
      return await this.service.updateSeoTask({
        where: params,
        data: data,
        select: {
          country: true,
          createdAt: true,
          id: true,
          keyword: true,
          language: true,
          location: true,
          results: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SeoTask })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SeoTask",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSeoTask(
    @common.Param() params: SeoTaskWhereUniqueInput
  ): Promise<SeoTask | null> {
    try {
      return await this.service.deleteSeoTask({
        where: params,
        select: {
          country: true,
          createdAt: true,
          id: true,
          keyword: true,
          language: true,
          location: true,
          results: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
