/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BacklinksUpdateManyWithoutUrlAnalysesInput } from "./BacklinksUpdateManyWithoutUrlAnalysesInput";

import {
  ValidateNested,
  IsOptional,
  IsNumber,
  Min,
  Max,
  IsInt,
  IsBoolean,
  IsString,
  MaxLength,
} from "class-validator";

import { Type } from "class-transformer";
import { BooleanCriteriaUpdateManyWithoutUrlAnalysesInput } from "./BooleanCriteriaUpdateManyWithoutUrlAnalysesInput";
import { ComparativeCriteriaUpdateManyWithoutUrlAnalysesInput } from "./ComparativeCriteriaUpdateManyWithoutUrlAnalysesInput";
import { PageSpeedUpdateManyWithoutUrlAnalysesInput } from "./PageSpeedUpdateManyWithoutUrlAnalysesInput";

@InputType()
class UrlAnalysisUpdateInput {
  @ApiProperty({
    required: false,
    type: () => BacklinksUpdateManyWithoutUrlAnalysesInput,
  })
  @ValidateNested()
  @Type(() => BacklinksUpdateManyWithoutUrlAnalysesInput)
  @IsOptional()
  @Field(() => BacklinksUpdateManyWithoutUrlAnalysesInput, {
    nullable: true,
  })
  backlinksItems?: BacklinksUpdateManyWithoutUrlAnalysesInput;

  @ApiProperty({
    required: false,
    type: () => BooleanCriteriaUpdateManyWithoutUrlAnalysesInput,
  })
  @ValidateNested()
  @Type(() => BooleanCriteriaUpdateManyWithoutUrlAnalysesInput)
  @IsOptional()
  @Field(() => BooleanCriteriaUpdateManyWithoutUrlAnalysesInput, {
    nullable: true,
  })
  booleanCriteriaItems?: BooleanCriteriaUpdateManyWithoutUrlAnalysesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  booleanScore?: number | null;

  @ApiProperty({
    required: false,
    type: () => ComparativeCriteriaUpdateManyWithoutUrlAnalysesInput,
  })
  @ValidateNested()
  @Type(() => ComparativeCriteriaUpdateManyWithoutUrlAnalysesInput)
  @IsOptional()
  @Field(() => ComparativeCriteriaUpdateManyWithoutUrlAnalysesInput, {
    nullable: true,
  })
  comparativeCriteriaItems?: ComparativeCriteriaUpdateManyWithoutUrlAnalysesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  comparativeScore?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  contentSize?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  googlePosition?: number | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isTarget?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => PageSpeedUpdateManyWithoutUrlAnalysesInput,
  })
  @ValidateNested()
  @Type(() => PageSpeedUpdateManyWithoutUrlAnalysesInput)
  @IsOptional()
  @Field(() => PageSpeedUpdateManyWithoutUrlAnalysesInput, {
    nullable: true,
  })
  pageSpeeds?: PageSpeedUpdateManyWithoutUrlAnalysesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  seoScore?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  url?: string | null;
}

export { UrlAnalysisUpdateInput as UrlAnalysisUpdateInput };
