/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BacklinksCreateNestedManyWithoutUrlAnalysesInput } from "./BacklinksCreateNestedManyWithoutUrlAnalysesInput";

import {
  ValidateNested,
  IsOptional,
  IsNumber,
  Min,
  Max,
  IsInt,
  IsBoolean,
  IsString,
  MaxLength,
} from "class-validator";

import { Type } from "class-transformer";
import { BooleanCriteriaCreateNestedManyWithoutUrlAnalysesInput } from "./BooleanCriteriaCreateNestedManyWithoutUrlAnalysesInput";
import { ComparativeCriteriaCreateNestedManyWithoutUrlAnalysesInput } from "./ComparativeCriteriaCreateNestedManyWithoutUrlAnalysesInput";
import { PageSpeedCreateNestedManyWithoutUrlAnalysesInput } from "./PageSpeedCreateNestedManyWithoutUrlAnalysesInput";

@InputType()
class UrlAnalysisCreateInput {
  @ApiProperty({
    required: false,
    type: () => BacklinksCreateNestedManyWithoutUrlAnalysesInput,
  })
  @ValidateNested()
  @Type(() => BacklinksCreateNestedManyWithoutUrlAnalysesInput)
  @IsOptional()
  @Field(() => BacklinksCreateNestedManyWithoutUrlAnalysesInput, {
    nullable: true,
  })
  backlinksItems?: BacklinksCreateNestedManyWithoutUrlAnalysesInput;

  @ApiProperty({
    required: false,
    type: () => BooleanCriteriaCreateNestedManyWithoutUrlAnalysesInput,
  })
  @ValidateNested()
  @Type(() => BooleanCriteriaCreateNestedManyWithoutUrlAnalysesInput)
  @IsOptional()
  @Field(() => BooleanCriteriaCreateNestedManyWithoutUrlAnalysesInput, {
    nullable: true,
  })
  booleanCriteriaItems?: BooleanCriteriaCreateNestedManyWithoutUrlAnalysesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  booleanScore?: number | null;

  @ApiProperty({
    required: false,
    type: () => ComparativeCriteriaCreateNestedManyWithoutUrlAnalysesInput,
  })
  @ValidateNested()
  @Type(() => ComparativeCriteriaCreateNestedManyWithoutUrlAnalysesInput)
  @IsOptional()
  @Field(() => ComparativeCriteriaCreateNestedManyWithoutUrlAnalysesInput, {
    nullable: true,
  })
  comparativeCriteriaItems?: ComparativeCriteriaCreateNestedManyWithoutUrlAnalysesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  comparativeScore?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  contentSize?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  googlePosition?: number | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isTarget?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => PageSpeedCreateNestedManyWithoutUrlAnalysesInput,
  })
  @ValidateNested()
  @Type(() => PageSpeedCreateNestedManyWithoutUrlAnalysesInput)
  @IsOptional()
  @Field(() => PageSpeedCreateNestedManyWithoutUrlAnalysesInput, {
    nullable: true,
  })
  pageSpeeds?: PageSpeedCreateNestedManyWithoutUrlAnalysesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  seoScore?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  url?: string | null;
}

export { UrlAnalysisCreateInput as UrlAnalysisCreateInput };
