/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BacklinksListRelationFilter } from "../../backlinks/base/BacklinksListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { BooleanCriteriaListRelationFilter } from "../../booleanCriteria/base/BooleanCriteriaListRelationFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { ComparativeCriteriaListRelationFilter } from "../../comparativeCriteria/base/ComparativeCriteriaListRelationFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { PageSpeedListRelationFilter } from "../../pageSpeed/base/PageSpeedListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";

@InputType()
class UrlAnalysisWhereInput {
  @ApiProperty({
    required: false,
    type: () => BacklinksListRelationFilter,
  })
  @ValidateNested()
  @Type(() => BacklinksListRelationFilter)
  @IsOptional()
  @Field(() => BacklinksListRelationFilter, {
    nullable: true,
  })
  backlinksItems?: BacklinksListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => BooleanCriteriaListRelationFilter,
  })
  @ValidateNested()
  @Type(() => BooleanCriteriaListRelationFilter)
  @IsOptional()
  @Field(() => BooleanCriteriaListRelationFilter, {
    nullable: true,
  })
  booleanCriteriaItems?: BooleanCriteriaListRelationFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  booleanScore?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ComparativeCriteriaListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ComparativeCriteriaListRelationFilter)
  @IsOptional()
  @Field(() => ComparativeCriteriaListRelationFilter, {
    nullable: true,
  })
  comparativeCriteriaItems?: ComparativeCriteriaListRelationFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  comparativeScore?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  contentSize?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  googlePosition?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  isTarget?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PageSpeedListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PageSpeedListRelationFilter)
  @IsOptional()
  @Field(() => PageSpeedListRelationFilter, {
    nullable: true,
  })
  pageSpeeds?: PageSpeedListRelationFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  seoScore?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  url?: StringNullableFilter;
}

export { UrlAnalysisWhereInput as UrlAnalysisWhereInput };
