/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BooleanCriteriaService } from "../booleanCriteria.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BooleanCriteriaCreateInput } from "./BooleanCriteriaCreateInput";
import { BooleanCriteria } from "./BooleanCriteria";
import { BooleanCriteriaFindManyArgs } from "./BooleanCriteriaFindManyArgs";
import { BooleanCriteriaWhereUniqueInput } from "./BooleanCriteriaWhereUniqueInput";
import { BooleanCriteriaUpdateInput } from "./BooleanCriteriaUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BooleanCriteriaControllerBase {
  constructor(
    protected readonly service: BooleanCriteriaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BooleanCriteria })
  @nestAccessControl.UseRoles({
    resource: "BooleanCriteria",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createBooleanCriteria(
    @common.Body() data: BooleanCriteriaCreateInput
  ): Promise<BooleanCriteria> {
    return await this.service.createBooleanCriteria({
      data: {
        ...data,

        urlAnalysis: data.urlAnalysis
          ? {
              connect: data.urlAnalysis,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        keywordInTitle: true,
        titleLength: true,
        updatedAt: true,

        urlAnalysis: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [BooleanCriteria] })
  @ApiNestedQuery(BooleanCriteriaFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BooleanCriteria",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async booleanCriteriaItems(
    @common.Req() request: Request
  ): Promise<BooleanCriteria[]> {
    const args = plainToClass(BooleanCriteriaFindManyArgs, request.query);
    return this.service.booleanCriteriaItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        keywordInTitle: true,
        titleLength: true,
        updatedAt: true,

        urlAnalysis: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BooleanCriteria })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BooleanCriteria",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async booleanCriteria(
    @common.Param() params: BooleanCriteriaWhereUniqueInput
  ): Promise<BooleanCriteria | null> {
    const result = await this.service.booleanCriteria({
      where: params,
      select: {
        createdAt: true,
        id: true,
        keywordInTitle: true,
        titleLength: true,
        updatedAt: true,

        urlAnalysis: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BooleanCriteria })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BooleanCriteria",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateBooleanCriteria(
    @common.Param() params: BooleanCriteriaWhereUniqueInput,
    @common.Body() data: BooleanCriteriaUpdateInput
  ): Promise<BooleanCriteria | null> {
    try {
      return await this.service.updateBooleanCriteria({
        where: params,
        data: {
          ...data,

          urlAnalysis: data.urlAnalysis
            ? {
                connect: data.urlAnalysis,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          keywordInTitle: true,
          titleLength: true,
          updatedAt: true,

          urlAnalysis: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BooleanCriteria })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BooleanCriteria",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBooleanCriteria(
    @common.Param() params: BooleanCriteriaWhereUniqueInput
  ): Promise<BooleanCriteria | null> {
    try {
      return await this.service.deleteBooleanCriteria({
        where: params,
        select: {
          createdAt: true,
          id: true,
          keywordInTitle: true,
          titleLength: true,
          updatedAt: true,

          urlAnalysis: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
